import requests

TOP_N = 30 

def get_top_coins():
    print(">>> Fetching Market Data from Binance.US...")
    url = "https://api.binance.us/api/v3/ticker/24hr"
    try:
        tickers = requests.get(url).json()
    except Exception as e:
        print(f"Error: {e}")
        return []

    usdt_pairs = [t for t in tickers if t['symbol'].endswith('USDT')]
    sorted_pairs = sorted(usdt_pairs, key=lambda x: float(x['quoteVolume']), reverse=True)
    
    unique_coins = []
    seen = set()
    
    bases = ['USDT', 'USD', 'BTC', 'ETH', 'BNB'] 
    for b in bases:
        if b not in seen:
            unique_coins.append(b)
            seen.add(b)

    for pair in sorted_pairs:
        symbol = pair['symbol'].replace('USDT', '')
        if symbol not in seen:
            unique_coins.append(symbol)
            seen.add(symbol)
        if len(unique_coins) >= TOP_N:
            break
            
    print("Unique coins: ", *unique_coins)
    return unique_coins

def generate_cpp_header(coins):
    quotes = ['USD', 'USDT', 'BTC', 'ETH', 'BNB']
    pairs = []
    
    for coin in coins:
        for q in quotes:
            if coin == q: continue
            s1 = f"{coin.lower()}{q.lower()}"
            if s1 not in pairs: pairs.append(s1)
                
    coin_to_idx = { c.lower(): i for i, c in enumerate(coins) }

    code = f"""#pragma once
#include <array>
#include <string_view>

// Auto-generated by generate_config.py

namespace Config {{

    // 1. Node List (Coins)
    constexpr int NUM_COINS = {len(coins)};
    constexpr std::array<std::string_view, NUM_COINS> COINS = {{
"""
    
    line = "        "
    for i, c in enumerate(coins):
        line += f'"{c}", '
        if (i + 1) % 8 == 0:
            code += line.rstrip() + "\n        "
            line = ""
    code += line.rstrip(", ") + "\n    };\n\n"

    code += f"""    // 2. Subscription Targets (Edges)
    constexpr int NUM_PAIRS = {len(pairs)};
    constexpr std::array<std::string_view, NUM_PAIRS> TARGET_PAIRS = {{
"""
    
    line = "        "
    for i, p in enumerate(pairs):
        line += f'"{p}", '
        if (i + 1) % 6 == 0:
            code += line.rstrip() + "\n        "
            line = ""
    code += line.rstrip(", ") + "\n    };\n"

    code += """
    // 3. Valid Edges (From -> To indices)
    struct EdgeDef { int u; int v; };
    // *2 because we add bidirectional edges (u->v and v->u)
    constexpr std::array<EdgeDef, NUM_PAIRS * 2> VALID_EDGES = {{ 
"""

    count = 0
    sorted_coins = sorted(coins, key=len, reverse=True)
    
    valid_pair_count = 0

    for pair in pairs:
        u_idx = -1
        v_idx = -1
        
        for coin in sorted_coins:
            coin_lower = coin.lower() 
            
            if pair.startswith(coin_lower):
                base_coin = coin_lower
                quote_coin = pair[len(base_coin):]
                
                if quote_coin in coin_to_idx:
                    u_idx = coin_to_idx[base_coin]
                    v_idx = coin_to_idx[quote_coin]
                    break 
        
        if u_idx != -1 and v_idx != -1:
            code += f"        {{ {u_idx}, {v_idx} }}, {{ {v_idx}, {u_idx} }}, \n"
            count += 2
            valid_pair_count += 1
        else:
            print(f"[Warning] Could not parse pair: {pair}")
            
    code += "    }};\n"
    code += "}\n"

    with open("Config.hpp", "w", encoding="utf-8") as f:
        f.write(code)
    
    print(f">>> Successfully generated 'Config.hpp'.")
    print(f"    - Coins: {len(coins)}")
    print(f"    - Pairs: {len(pairs)}")
    print(f"    - Valid Edges Parsed: {valid_pair_count} pairs ({valid_pair_count * 2} edges)")

if __name__ == "__main__":
    coins = get_top_coins()
    if coins:
        generate_cpp_header(coins)
